
# Site settings
title: TIANJIA HUANG
name: Tianjia Huang
subtitle:  Researcher
email: huangtj@tamu.edu
description: >
   Researcher
baseurl: ""
url: "https://github.com/TianjiaHuang/TianjiaHuang.github.io/"
github_username:  TianjiaHuang
disqus_baseurl: "https://github.com/TianjiaHuang/TianjiaHuang.github.io/"
disqus_shortname: https-tianjiahuang-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tianjia Huang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: TianjiaHuang
    url: https://github.com/TianjiaHuang
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Tianjia Huang
    url: https://www.linkedin.com/in/tianjiahuang/
    desc: Connect with me on LinkedIn
    share: true
